All:
	@echo "----------Building project:[ forst_work_1 - Debug ]----------"
	@cd "forst_work_1" && $(MAKE) /nologo /f  "forst_work_1.mk"
clean:
	@echo "----------Cleaning project:[ forst_work_1 - Debug ]----------"
	@cd "forst_work_1" && $(MAKE) /nologo /f  "forst_work_1.mk" clean
.PHONY: clean All

