services:
  web-fe:
    # build command build from -Dockerfile on same level where docker-compose is
    build: .
    command: python app.py
    ports:
      - 5000:5000
  redis:
    image: "redis:alpine"
    ports:
      - 6379
