version: '3.8'
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app/

  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=root
    ports:
      - "5432:5432"
    volumes:
      - ./databse-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql