version: '3.8'
services:

  postgres:
    image: postgres:14
    container_name: postgres-tutorial
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      # - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # - POSTGRES_USER=${POSTGRES_USER}
      # - POSTGRES_DB=${POSTGRES_DB}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080

volumes:
  postgres:
    name: postgres-tutorial
